gistest.pdf: gistest.tex intro.tex bibliography.bib related.tex abstract.tex conclusions.tex langchanges.tex quicktests.tex normgen.tex regression.tex sandbox.tex toolchanges.tex tstl.tex faults.tex
	pdflatex gistest.tex
	bibtex gistest
	pdflatex gistest.tex
	pdflatex gistest.tex
