maintstl.pdf: maintstl.tex intro.tex bibliography.bib related.tex abstract.tex conclusions.tex langchanges.tex quicktests.tex normgen.tex regression.tex sandbox.tex toolchanges.tex tstl.tex faults.tex theharness.tex standalone.tex future.tex
	pdflatex maintstl.tex
	bibtex maintstl
	pdflatex maintstl.tex
	pdflatex maintstl.tex
