normalize.pdf: normalize.tex intro.tex bibliography.bib casestudies.tex related.tex abstract.tex conclusions.tex formal.tex
	pdflatex normalize.tex
	bibtex normalize
	pdflatex normalize.tex
	pdflatex normalize.tex
