maintstl.pdf: maintstl.tex intro.tex bibliography.bib related.tex abstract.tex conclusions.tex  tools.tex intro.tex lang.tex bugs.tex
	pdflatex maintstl.tex
	bibtex maintstl
	pdflatex maintstl.tex
	pdflatex maintstl.tex
